# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

#parameters:
  #- name: demoparam
   # type: string
   # values:
     # - one
     # - two
     # - three
    #default: one
resources:
 pipelines:
  - pipeline: 'sharniandapplication'
    source: 'apkAndroidCrazy01'
    branch: master

steps:  
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '6ff3b86d-f7c4-4f43-993e-7500d51e98fb'
    pipeline: '14'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    downloadType: 'single'
    artifactName: '$(resources.pipeline.sharniandapplication.runId)'
    downloadPath: '$(System.ArtifactsDirectory)'